[versions]
kotlinVersion = "1.9.24"
springBootVersion = "3.3.2"
[bundles]

[libraries]

[plugins]
spring-boot = {id = "org.springframework.boot", version.ref = "springBootVersion"}
#id("io.spring.dependency-management") version "1.1.6"